<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <!--Explicit import Directory.Build.props (for old-style csproj)-->
  <Import Project="..\Directory.Build.props" Condition="'$(UsingMicrosoftNETSdk)' != 'true'"/>
  
  <Import Project="$(SlnDir)\UsedPackages.version" />
  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="$(SkiaSharpVersion)" />
    <PackageReference Include="SkiaSharp.HarfBuzz" Version="$(HarfBuzzVersion)" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="$(SkiaSharpVersion)" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Version="14.2.1.1" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="$(CodeAnalysisCSharpVersion)" />
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic" Version="$(CodeAnalysisVisualBasicVersion)" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE.md">
      <Pack>True</Pack>
      <Visible>false</Visible>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>
</Project>
